# Generated by Django 4.2 on 2023-05-04 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respond',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='api.vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='respond',
            unique_together={('user', 'vacancy')},
        ),
    ]
