# Generated by Django 4.2 on 2023-05-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_respond'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respond',
            unique_together={('user', 'vacancy')},
        ),
    ]
